# Generated by Django 5.1.7 on 2025-03-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_deliveryadresss_order_deliveryinstructions_and_more'),
        ('Restuarant', '0002_alter_menuitem_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='menuitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restuarant.menuitem'),
            preserve_default=False,
        ),
    ]
