# Generated by Django 5.1.7 on 2025-03-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_order_restaurant_order_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='DeliveryAdresss',
            new_name='DeliveryAdress',
        ),
    ]
